server:
  port: 8686

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.h2.Driver
    name: product-db
    password: ''
    sql-script-encoding: UTF-8
    url: jdbc:h2:file:./src/main/resources/database/product-db
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


